; ESP32 Classic Bluetooth A2DP source for Adafruit ESP32 Feather V2.

[env:esp_a2dp_ag]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = espidf

board_build.sdkconfig = sdkconfig.esp_a2dp_ag
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-5B1F0129841
upload_port = /dev/cu.usbserial-5B1F0129841
upload_speed = 460800

build_flags =
    -D SAMPLE_RATE=44100
    -D I2S_BCLK_GPIO=5
    -D I2S_WS_GPIO=25
    -D I2S_DIN_GPIO=21
    -D RGB_LED_GPIO=0
    -D RGB_LED_POWER_GPIO=2
    -D BT_DEVICE_NAME=\"ESP-A2DP-Source\"
    -D BT_REMOTE_NAME=\"\"
